from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('online', views.online, name='online'),
    path('gotowki', views.gotowki, name='gotowki'),
    path('koszty_faktury', views.koszty_faktury, name='koszty_faktury'),
    path('koszty_kontrahenci', views.koszty_kontrahenci, name='koszty_kontrahenci'),
    path('faktury_wyszukaj', views.faktury_wyszukaj, name='faktury_wyszukaj'),
    path('faktury_wykaz', views.faktury_wykaz, name='faktury_wykaz'),
    path('towar_faktury', views.towar_faktury, name='towar_faktury'),
    path('przelewy_wykaz', views.przelewy_wykaz, name='przelewy_wykaz'),
    path('przelewy_bufor', views.przelewy_bufor, name='przelewy_bufor'),
    path('towar_dostawcy', views.towar_dostawcy, name='towar_dostawcy'),
    path('hurtownie_import_danych', views.hurtownie_import_danych, name='hurtownie_import_danych'),
    path('hurtownie_faktury', views.hurtownie_faktury, name='hurtownie_faktury'),
    path('hurtownie_zestawienia', views.hurtownie_zestawienia, name='hurtownie_zestawienia'),
    path('hurtownie_poziom_zakupow', views.hurtownie_poziom_zakupow, name='hurtownie_poziom_zakupow'),
    path('hurtownie_maile', views.hurtownie_maile, name='hurtownie_maile'),
    path('pracownicy_dane', views.pracownicy_dane, name='pracownicy_dane'),
    path('pracownicy_urlopy', views.pracownicy_urlopy, name='pracownicy_urlopy'),
    path('pracownicy_wyplaty_dane', views.pracownicy_wyplaty_dane, name='pracownicy_wyplaty_dane'),
    path('pracownicy_wyplaty_przelewy', views.pracownicy_wyplaty_przelewy, name='pracownicy_wyplaty_przelewy'),
    path('pracownicy_wyplaty_zakupy', views.pracownicy_wyplaty_zakupy_maile, name='pracownicy_wyplaty_zakupy'),
    path('rozne_fundusze_l', views.rozne_fundusze_l, name='rozne_fundusze_l'),
    path('rozne_karty_hallera', views.rozne_karty_hallera, name='rozne_karty_hallera'),
    path('czynsze', views.rozne_czynsze, name='czynsze'),
    path('biala_lista', views.rozne_biala_lista, name='biala_lista'),
    path('dyzury', views.rozne_dyzury, name='dyzury'),
    path('reklamowiki_raport', views.rozne_reklamowki, name='reklamowiki_raport'),
    path('todo_list', views.rozne_todo_list, name='todo_list'),
    path('archiwa', views.rozne_archiwa, name='archiwa'),
    path('wyciagi', views.sage_wyciagi, name='wyciagi'),
    path('nowy_wyciag', views.sage_nowy_wyciag, name='nowy_wyciag'),
    path('sage_eksport', views.sage_eksport, name='sage_eksport'),
    path('sage_konta_specjalne', views.sage_konta_specjalne, name='sage_konta_specjalne'),
    path('sage_kontrahenci_stali', views.sage_kontrahenci_stali, name='sage_kontrahenci_stali'),
    path('sage_rf_pliki', views.sage_rf_pliki, name='sage_rf_pliki'),
    path('testy_rozne', views.testy_rozne, name='testy_rozne'),
]